---
sidebar: sidebar 
permalink: concept-storage-management.html 
keywords: provisioning, capacity management, storage provisioning, manual, automatic, advanced allocation, aggregates, thin provisioning, free space, mode, BlueXP, NetApp Consolecloud manager 
summary: La console offre una gestione semplificata e avanzata dello storage Cloud Volumes ONTAP . 
---
= Gestione dello storage Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console offre una gestione semplificata e avanzata dello storage Cloud Volumes ONTAP .


CAUTION: È necessario creare ed eliminare tutti i dischi e gli aggregati direttamente dalla Console. Non dovresti eseguire queste azioni da un altro strumento di gestione. Ciò potrebbe compromettere la stabilità del sistema, ostacolare la possibilità di aggiungere dischi in futuro e potenzialmente generare commissioni ridondanti per il provider cloud.



[[storage-provisioning]]
== Provisioning dello storage

La Console semplifica il provisioning dello storage per Cloud Volumes ONTAP acquistando dischi e gestendo gli aggregati per te.  Devi solo creare volumi.  Se lo desideri, puoi utilizzare un'opzione di allocazione avanzata per effettuare autonomamente il provisioning degli aggregati.



[[simplified-provisioning]]
=== Provisioning semplificato

Gli aggregati forniscono spazio di archiviazione cloud ai volumi.  La console crea aggregati per te quando avvii un'istanza e quando esegui il provisioning di volumi aggiuntivi.

Quando si crea un volume, la Console esegue una delle tre operazioni seguenti:

* Colloca il volume su un aggregato esistente che dispone di spazio libero sufficiente.
* Colloca il volume su un aggregato esistente acquistando più dischi per quell'aggregato.
* Acquista dischi per un nuovo aggregato e posiziona il volume su quell'aggregato.


La console determina dove posizionare un nuovo volume prendendo in considerazione diversi fattori: la dimensione massima di un aggregato, se il thin provisioning è abilitato e le soglie di spazio libero per gli aggregati.



[[advanced-allocation]]
=== Assegnazione anticipata

È anche possibile gestire gli aggregati. link:task-create-aggregates.html["Dalla pagina *Assegnazione avanzata*"] , è possibile creare nuovi aggregati che includono un numero specifico di dischi, aggiungere dischi a un aggregato esistente e creare volumi in aggregati specifici.



[[capacity-management]]
== Gestione della capacità

L'amministratore dell'organizzazione o dell'account può configurare la Console in modo che ti informi sulle decisioni relative alla capacità di archiviazione o che gestisca automaticamente i requisiti di capacità per te.

Questo comportamento è determinato dalla _Modalità di gestione della capacità_ su un agente della console.  La modalità di gestione della capacità interessa tutti i sistemi Cloud Volumes ONTAP gestiti da quell'agente della console.  Se si dispone di un altro agente Console, è possibile configurarlo in modo diverso.



[[automatic-capacity-management]]
=== Gestione automatica della capacità

Per impostazione predefinita, la modalità di gestione della capacità è impostata su automatica.  In questa modalità, la console controlla il rapporto di spazio libero ogni 15 minuti per determinare se tale rapporto scende al di sotto della soglia specificata.  Se è necessaria maggiore capacità, avvia l'acquisto di nuovi dischi, elimina le raccolte di dischi non utilizzate (aggregati), sposta i volumi tra gli aggregati secondo necessità e tenta di impedire guasti ai dischi.

Gli esempi seguenti illustrano il funzionamento di questa modalità:

* Se un aggregato raggiunge la soglia di capacità e ha spazio per altri dischi, la Console acquista automaticamente nuovi dischi per quell'aggregato, in modo che i volumi possano continuare a crescere.
* Se un aggregate raggiunge la soglia di capacità e non può supportare ulteriori dischi, la Console sposta automaticamente un volume da tale aggregate a un aggregate con capacità disponibile o a un nuovo aggregate.
+
Se la Console crea un nuovo aggregate per il volume, sceglie una dimensione del disco che si adatta alla dimensione di quel volume.

+
Nota che lo spazio libero è ora disponibile sull'aggregato originale. I volumi esistenti o i nuovi volumi possono utilizzare quello spazio. In questo scenario, lo spazio non può essere restituito al cloud provider.

* Se un aggregato non contiene volumi per più di 12 ore, la Console lo elimina.




==== Gestione delle LUN con gestione automatica della capacità

La gestione automatica della capacità della Console non si applica alle LUN.  Quando crea un LUN, disabilita la funzionalità di aumento automatico.



[[manual-capacity-management]]
=== Gestione manuale della capacità

Se l'amministratore dell'organizzazione o dell'account imposta la *Modalità di gestione della capacità* su manuale, la Console ti informa di intraprendere le azioni appropriate per le decisioni sulla capacità. Gli stessi esempi descritti nella modalità automatica si applicano alla modalità manuale, ma spetta a te accettare le azioni.

.Link correlati
* link:task-manage-capacity-settings.html["Scopri come modificare la modalità di gestione della capacità"] .
* Per informazioni sul provisioning in AWS, consulta link:reference-configs-aws.html["Provisioning del disco per gli aggregati in AWS"].

