---
sidebar: sidebar 
permalink: concept-write-speed.html 
keywords: write speed, high write speed, normal write speed, nvfail, writing speed, ldm, low durability mode 
summary: 'NetApp Console consente di scegliere una velocità di scrittura normale o elevata per Cloud Volumes ONTAP.  Prima di scegliere una velocità di scrittura, è necessario comprendere le differenze tra le impostazioni normale e alta, nonché i rischi e i consigli relativi all"utilizzo di una velocità di scrittura elevata.' 
---
= velocità di scrittura
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp Console consente di scegliere una velocità di scrittura normale o elevata per la maggior parte delle configurazioni Cloud Volumes ONTAP .  Prima di scegliere una velocità di scrittura, è necessario comprendere le differenze tra le impostazioni normale e alta, nonché i rischi e i consigli relativi all'utilizzo di una velocità di scrittura elevata.



== Velocità di scrittura normale

Quando si sceglie la velocità di scrittura normale, i dati vengono scritti direttamente sul disco.  Quando i dati vengono scritti direttamente su disco, si riduce la probabilità di perdita di dati in caso di interruzione imprevista del sistema o di un guasto a cascata che comporta un'interruzione imprevista del sistema (solo coppie HA).

L'opzione predefinita è la velocità di scrittura normale.



== Alta velocità di scrittura

Quando si sceglie un'elevata velocità di scrittura, i dati vengono memorizzati in un buffer nella memoria prima di essere scritti sul disco, il che garantisce prestazioni di scrittura più rapide.  A causa di questa memorizzazione nella cache, esiste il rischio di perdita di dati in caso di interruzione imprevista del sistema.

La quantità di dati che può andare persa in caso di interruzione imprevista del sistema è pari all'intervallo degli ultimi due punti di coerenza.  Un punto di coerenza è l'atto di scrivere dati memorizzati nel buffer su disco.  Un punto di coerenza si verifica quando il registro di scrittura è pieno o dopo 10 secondi (a seconda di quale evento si verifica per primo).  Tuttavia, le prestazioni dello storage fornito dal tuo provider cloud possono influire sul tempo di elaborazione del punto di coerenza.



=== Quando utilizzare un'elevata velocità di scrittura

Un'elevata velocità di scrittura è una buona scelta se sono richieste prestazioni di scrittura rapide per il carico di lavoro e si può resistere al rischio di perdita di dati in caso di interruzione imprevista del sistema o di un guasto a cascata che comporta un'interruzione imprevista del sistema (solo coppie HA).



=== Raccomandazioni per l'utilizzo di velocità di scrittura elevate

Se si abilita un'elevata velocità di scrittura, è necessario garantire la protezione da scrittura a livello di applicazione o che le applicazioni siano in grado di tollerare la perdita di dati, qualora si verifichi.

ifdef::aws[]



=== Elevata velocità di scrittura con una coppia HA in AWS

Se si prevede di abilitare un'elevata velocità di scrittura su una coppia HA in AWS, è necessario comprendere la differenza nei livelli di protezione tra una distribuzione con più zone di disponibilità (AZ) e una distribuzione con una sola AZ.  L'implementazione di una coppia HA su più AZ garantisce maggiore resilienza e può contribuire a ridurre il rischio di perdita di dati.

link:concept-ha.html["Scopri di più sulle coppie HA in AWS"] .

endif::aws[]



=== Configurazioni che supportano un'elevata velocità di scrittura

Non tutte le configurazioni Cloud Volumes ONTAP supportano velocità di scrittura elevate.  Per impostazione predefinita, queste configurazioni utilizzano la velocità di scrittura normale.

ifdef::aws[]



==== AWS

Se si utilizza un sistema a nodo singolo, Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con tutti i tipi di istanza.

A partire dalla versione 9.8, Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con coppie HA quando si utilizzano quasi tutti i tipi di istanze EC2 supportati, ad eccezione di m5.xlarge e r5.xlarge.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-aws.html["Scopri di più sulle istanze Amazon EC2 supportate da Cloud Volumes ONTAP"^] .

endif::aws[]

ifdef::azure[]



==== Azzurro

Se si utilizza un sistema a nodo singolo, Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con tutti i tipi di VM.

Se si utilizza una coppia HA, Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con diversi tipi di VM, a partire dalla versione 9.8.  Vai al https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-azure.html["Note sulla versione Cloud Volumes ONTAP"^] per visualizzare i tipi di VM che supportano un'elevata velocità di scrittura.

endif::azure[]

ifdef::gcp[]



==== Google Cloud

Se si utilizza un sistema a nodo singolo, Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con tutti i tipi di macchine.

Se si utilizza una coppia HA, Cloud Volumes ONTAP supporta un'elevata velocità di scrittura con diversi tipi di VM, a partire dalla versione 9.13.0.  Vai al https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html#supported-configurations-by-license["Note sulla versione Cloud Volumes ONTAP"^] per visualizzare i tipi di VM che supportano un'elevata velocità di scrittura.

https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-configs-gcp.html["Scopri di più sui tipi di macchine Google Cloud supportati da Cloud Volumes ONTAP"^] .

endif::gcp[]



== Come selezionare una velocità di scrittura

È possibile scegliere una velocità di scrittura quando si aggiunge un nuovo sistema Cloud Volumes ONTAP e si puòlink:task-modify-write-speed.html["modificare la velocità di scrittura per un sistema esistente"] .



== Cosa aspettarsi in caso di perdita di dati

Se si verifica una perdita di dati a causa dell'elevata velocità di scrittura, l'Event Management System (EMS) segnala i due eventi seguenti:

* Cloud Volumes ONTAP 9.12.1 o versione successiva
+
 NOTICE nv.data.loss.possible: An unexpected shutdown occurred while in high write speed mode, which possibly caused a loss of data.
* Cloud Volumes ONTAP da 9.11.0 a 9.11.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown with High Write Speed mode"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect..
* Cloud Volumes ONTAP da 9.8 a 9.10.1
+
 DEBUG nv.check.failed: NVRAM check failed with error "NVRAM disabled due to dirty shutdown"
+
 ERROR wafl.root.content.changed: Contents of the root volume '' might have changed. Verify that all recent configuration changes are still in effect.


Quando ciò accade, Cloud Volumes ONTAP dovrebbe essere in grado di avviarsi e continuare a fornire dati senza l'intervento dell'utente.



== Come interrompere l'accesso ai dati in caso di perdita di dati

Se si teme la perdita di dati e si desidera che le applicazioni smettano di funzionare in caso di perdita di dati e che l'accesso ai dati venga ripreso dopo aver risolto correttamente il problema della perdita di dati, è possibile utilizzare l'opzione NVFAIL dalla CLI per raggiungere tale obiettivo.

Per abilitare l'opzione NVFAIL:: `vol modify -volume <vol-name> -nvfail on`
Per controllare le impostazioni NVFAIL:: `vol show -volume <vol-name> -fields nvfail`
Per disabilitare l'opzione NVFAIL:: `vol modify -volume <vol-name> -nvfail off`


Quando si verifica una perdita di dati, un volume NFS o iSCSI con NVFAIL abilitato dovrebbe smettere di fornire dati (non vi è alcun impatto su CIFS, che è un protocollo stateless).  Per maggiori dettagli, fare riferimento a https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-mcc-mgmt-dr/GUID-40D04B8A-01F7-4E87-8161-E30BD80F5B7F.html["In che modo NVFAIL influisce sull'accesso ai volumi NFS o LUN"^] .

Per controllare lo stato NVFAIL:: `vol show -fields in-nvfailed-state`


Dopo aver risolto correttamente il problema della perdita di dati, è possibile cancellare lo stato NVFAIL e il volume sarà disponibile per l'accesso ai dati.

Per cancellare lo stato NVFAIL:: `vol modify -volume <vol-name> -in-nvfailed-state false`

