---
sidebar: sidebar 
permalink: concept-licensing-charging.html 
keywords: capacity-based license charging, consumption for licenses, pricing for licenses, CVO licensing, CVO charging, SnapLock charging, CIFS charging, audit volumes, primary volumes, volume-based charging 
summary: Acquisire familiarità con la tariffazione, il modello di consumo, i prezzi e le configurazioni delle licenze basate sulla capacità. 
---
= Scopri di più sulle licenze basate sulla capacità per Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La licenza basata sulla capacità di Cloud Volumes ONTAP determina come vengono fatturati la capacità di archiviazione, i pacchetti e gli eventuali superamenti. Usa queste informazioni per capire la fatturazione e il consumo di capacità, soprattutto per le implementazioni in modalità standard.

Le implementazioni in modalità privata possono utilizzare pacchetti Essentials basati sulla capacità solo in un modello Bring-Your-Own License (BYOL). Per i dettagli sulle licenze per le implementazioni in modalità privata, consulta link:concept-license-management.html["Scopri Cloud Volumes ONTAP BYOL"^].



[[consumption-models-and-purchase-options]]
== Modelli di consumo e opzioni di acquisto

Sono disponibili pacchetti di licenze basati sulla capacità con i seguenti modelli di consumo o opzioni di acquisto:

* *Abbonamenti al marketplace/Contratto annuale*: Un contratto annuale dal marketplace del tuo cloud provider. Le implementazioni in modalità privata non supportano gli abbonamenti al marketplace.
* *PAYGO*: Un abbonamento pay-as-you-go (PAYGO) è un abbonamento orario dal marketplace del tuo provider cloud.
* *BYOL*: Bring-Your-Own License (BYOL). Una licenza acquistata da NetApp che può essere utilizzata per distribuire Cloud Volumes ONTAP in qualsiasi cloud provider.
+

NOTE: NetApp ha limitato l'acquisto, l'estensione e il rinnovo delle licenze BYOL e ha limitato la disponibilità in scenari specifici, come nelle implementazioni in modalità privata. Per ulteriori informazioni, consulta  https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/whats-new.html#restricted-availability-of-byol-licensing-for-cloud-volumes-ontap["Disponibilità limitata delle licenze BYOL per Cloud Volumes ONTAP"^].



Notare quanto segue:

* Se acquisti una licenza BYOL da NetApp, devi anche abbonarti all'offerta PAYGO nel marketplace del tuo cloud provider. NetApp ha limitato il modello di licensing BYOL per le implementazioni in modalità standard. Quando la tua licenza BYOL scade, sostituiscila con un abbonamento al marketplace del cloud.
+
L'addebito avviene sempre per primo sulla tua licenza, ma nei seguenti casi ti verrà addebitata la tariffa oraria del marketplace:

+
** Se superi la capacità autorizzata
** Se scade il termine della tua licenza


* Se disponi di una licenza BYOL e di un contratto annuale con un marketplace, i tuoi consumi e gli eventuali extra vengono addebitati in base alle preferenze di fatturazione che hai impostato. Per capire come sei addebitato, consulta link:concept-licensing-charging.html#billing-preferences-and-overages["Preferenze di fatturazione e superamenti"].
* Solo i sistemi a nodo singolo con BYOL sono supportati nelle regioni della Cina. Le distribuzioni nella regione della Cina sono esenti dalle restrizioni di licenza BYOL.




[[how-you-are-charged-for-supported-storage-types-and-packages]]
== Come vengono addebitati i tipi di archiviazione e i pacchetti supportati

La fatturazione in Cloud Volumes ONTAP si basa su una serie di fattori, come pacchetti e tipi di volume. I pacchetti di licenze basati sulla capacità sono disponibili con Cloud Volumes ONTAP 9.7 e versioni successive.

Le sezioni seguenti spiegano cosa viene addebitato, dove si applicano i minimi e come vengono fatturate le eccedenze.

Per dettagli sui prezzi, vai alla  https://bluexp.netapp.com/pricing/["Sito web NetApp Console"^].



[[storage-vms]]
=== VM di archiviazione

* Non ci sono costi di licenza aggiuntivi per le storage VM (SVM) aggiuntive dedicate all'erogazione dei dati, ma c'è un addebito minimo di capacità di quattro TiB per ogni SVM dedicata all'erogazione dei dati.
* Le SVM di disaster recovery vengono fatturate in base alla capacità fornita.




[[ha-pairs]]
=== coppie HA

Per le coppie HA, ti verrà addebitata solo la capacità fornita su un nodo.  Non ti verrà addebitato alcun costo per i dati che vengono replicati in modo sincrono sul nodo partner.



[[flexclone-and-flexcache-volumes]]
=== Volumi FlexClone e FlexCache

* Non ti verrà addebitato alcun costo per la capacità utilizzata dai volumi FlexClone .
* I volumi FlexCache di origine e di destinazione sono considerati dati primari e addebitati in base allo spazio fornito.




[[readwrite-volumes]]
=== Volumi di lettura/scrittura

Un volume scrivibile (lettura/scrittura) è un volume primario. Il sistema addebita la capacità allocata in base alla tariffa minima per storage VM (SVM). Esempi includono volumi di lettura/scrittura FlexVol, volumi di audit SnapLock e volumi di audit CIFS/NFS. Tutti i volumi dati creati dall'utente vengono addebitati in base al tuo abbonamento e al tipo di pacchetto. I volumi interni di ONTAP, come i volumi root SVM, non vengono addebitati perché vengono creati automaticamente e non possono memorizzare dati.



[[essentials-packages]]
=== Pacchetti essenziali

Il pacchetto Essentials prevede una fatturazione in base al tipo di deployment (HA o nodo singolo) e al tipo di volume (primario o secondario). I prezzi, dal più alto al più basso, sono _Essentials Primary HA_, _Essentials Primary Single Node_, _Essentials Secondary HA_ e _Essentials Secondary Single Node_. Se acquisti un contratto marketplace o accetti un'offerta privata, il costo della capacità è lo stesso per qualsiasi tipo di deployment o di volume.

La concessione delle licenze si basa interamente sul tipo di volume creato nei sistemi Cloud Volumes ONTAP :

* Nodo singolo Essentials: volumi di lettura/scrittura creati su un sistema Cloud Volumes ONTAP utilizzando un solo nodo ONTAP .
* Essentials HA: volumi di lettura/scrittura che utilizzano due nodi ONTAP che possono eseguire il failover l'uno sull'altro per un accesso ai dati senza interruzioni.
* Nodo singolo secondario Essentials: volumi di tipo Data Protection (DP) (in genere volumi di destinazione SnapMirror o SnapVault di sola lettura) creati su un sistema Cloud Volumes ONTAP utilizzando un solo nodo ONTAP .
+

NOTE: Se un volume DP di sola lettura diventa un volume primario, la Console lo considera come dati primari e calcola i costi in base al tempo in cui il volume rimane in modalità di lettura/scrittura. Se il volume torna a essere di sola lettura, la Console lo considera come dati secondari e addebita i costi in base alla licenza più appropriata presente nella Console.

* Essentials Secondary HA: volumi di tipo Data Protection (DP) (in genere volumi di destinazione SnapMirror o SnapVault di sola lettura) creati su un sistema Cloud Volumes ONTAP utilizzando due nodi ONTAP che possono eseguire il failover l'uno sull'altro per un accesso ai dati senza interruzioni.




[[minimum-charge]]
== Costo minimo

È previsto un costo minimo di 4 TiB per ogni VM di archiviazione dati che abbia almeno un volume primario (lettura-scrittura).  Se la somma dei volumi primari è inferiore a 4 TiB, la Console applica la tariffa minima di 4 TiB a quella VM di archiviazione.

Se non hai ancora effettuato il provisioning di alcun volume, la tariffa minima non verrà applicata.

Per il pacchetto Essentials, la tariffa per la capacità minima di 4 TiB non si applica alle VM di archiviazione che contengono solo volumi secondari (di protezione dei dati). Ad esempio, se si dispone di una VM di archiviazione con 1 TiB di dati secondari, verrà addebitato solo quel 1 TiB di dati. Con il tipo di pacchetto Professional, la capacità minima di ricarica di 4 TiB si applica indipendentemente dal tipo di volume.



[[billing-preferences-and-overages]]
== Preferenze di fatturazione e superamenti

Puoi scegliere la modalità di addebito nella sezione * Licenses and subscriptions* della Console. Si verificano eccedenze quando l'utilizzo supera la capacità specificata nel pacchetto di licenza o nell'abbonamento annuale.

* * Licenze NetApp prima*: in questo modello, l'utilizzo viene addebitato prima sulla capacità del pacchetto di licenze (BYOL). Se superi la capacità della tua licenza, le eccedenze verranno addebitate in base all'abbonamento annuale al marketplace o alle tariffe orarie on-demand del marketplace (PAYGO). Se la licenza BYOL scade, è necessario passare a un modello di licenza basato sulla capacità tramite i marketplace cloud. Per informazioni, fare riferimento a link:task-convert-node-capacity.html["Convertire una licenza basata su nodi Cloud Volumes ONTAP in una licenza basata sulla capacità"].
* *Solo abbonamenti al Marketplace*: con questo modello, l'utilizzo viene addebitato innanzitutto sull'abbonamento annuale al Marketplace. Ogni utilizzo aggiuntivo verrà addebitato in base alle tariffe orarie on-demand del marketplace (PAYGO). L'eventuale capacità di licenza non utilizzata non viene presa in considerazione ai fini della fatturazione.


Per ulteriori informazioni sulle preferenze di fatturazione, fare riferimento a https://docs.netapp.com/us-en/console-licenses-subscriptions/concept-billing-preferences.html["Scopri di più sulle preferenze di fatturazione per licenze e abbonamenti"^].



[[how-overages-are-charged-for-essentials-licenses]]
=== Come vengono addebitati gli eccessi per le licenze Essentials

Se acquisti una licenza Essentials da NetApp (BYOL) e superi la capacità concessa in licenza per uno specifico pacchetto Essentials, la Console addebita le eccedenze su una licenza Essentials più costosa (se ne hai una con capacità disponibile).  La Console utilizza innanzitutto la capacità disponibile per cui hai pagato prima di addebitare l'importo sul marketplace.  Se non è disponibile capacità con la tua licenza BYOL, la capacità eccedente verrà addebitata in base alle tariffe orarie on-demand del marketplace (PAYGO) e aggiunta alla tua fattura mensile.

Analogamente, se hai un contratto annuale con il marketplace o un'offerta privata con più pacchetti Essentials e il tuo utilizzo supera la capacità concordata per una specifica implementazione e tipologia di volume, la Console addebita le eccedenze a un pacchetto Essentials di prezzo superiore che ha capacità disponibile. Dopo che tale capacità è esaurita, l'eccedenza restante viene fatturata alle tariffe orarie on-demand (PAYGO) del marketplace e aggiunta alla tua fattura mensile.

Per informazioni sulla fatturazione delle licenze Essentials, consulta <<Pacchetti essenziali>>.

Ecco un esempio. Supponiamo che tu abbia le seguenti licenze per il pacchetto Essentials:

* Una licenza _Essentials Secondary HA_ da 500 TiB con capacità impegnata di 500 TiB
* Una licenza _Essentials Single Node_ da 500 TiB che ha solo 100 TiB di capacità impegnata


Altri 50 TiB sono forniti su una coppia HA con volumi secondari.  Invece di addebitare quei 50 TiB a PAYGO, la Console addebita l'eccedenza di 50 TiB sulla licenza _Essentials Single Node_.  Questa licenza ha un prezzo più alto rispetto a _Essentials Secondary HA_, ma utilizza una licenza che hai già acquistato e non aggiungerà costi alla tua fattura mensile.

In *Amministrazione > Licenses and subscriptions*, puoi vedere 50 TiB addebitati sulla licenza _Essentials Single Node_.

Ecco un altro esempio.  Supponiamo che tu abbia le seguenti licenze per il pacchetto Essentials:

* Una licenza _Essentials Secondary HA_ da 500 TiB con capacità impegnata di 500 TiB
* Una licenza _Essentials Single Node_ da 500 TiB che ha solo 100 TiB di capacità impegnata


Altri 100 TiB sono forniti su una coppia HA con volumi primari.  La licenza acquistata non dispone della capacità impegnata per _Essentials Primary HA_.  La licenza _Essentials Primary HA_ ha un prezzo più alto rispetto alle licenze _Essentials Primary Single Node_ e _Essentials Secondary HA_.

In questo esempio, la Console addebita le eccedenze alla tariffa di mercato per i 100 TiB aggiuntivi.  Gli addebiti per il superamento del limite massimo appariranno sulla tua fattura mensile.



[[change-license-packages]]
== Modifica i pacchetti di licenza

Dopo il deployment, puoi cambiare il pacchetto di un sistema Cloud Volumes ONTAP che utilizza il licensing basato sulla capacità. Ad esempio, se hai effettuato il deployment di un sistema Cloud Volumes ONTAP con il pacchetto Essentials, puoi cambiarlo con il pacchetto Professional se cambiano le esigenze della tua azienda. link:task-manage-capacity-licenses.html["Scopri come cambiare i metodi di ricarica"].

NetApp sta gradualmente eliminando le licenze basate sui nodi a favore delle licenze basate sulla capacità. Le licenze basate sui nodi rimangono disponibili in alcuni sistemi meno recenti, come quelli dei clienti USPS e le implementazioni in Cina. Se hai una licenza basata sui nodi, puoi convertirla in una licenza basata sulla capacità. Per informazioni sulla conversione delle licenze basate sui nodi in licenze basate sulla capacità, consulta link:task-convert-node-capacity.html["Convertire una licenza basata su nodi in una licenza basata sulla capacità"].



[[capacity-limit]]
== Limite di capacità

Nel modello di licenza basato sulla capacità, ogni sistema Cloud Volumes ONTAP supporta la suddivisione in livelli per l'archiviazione di oggetti e la capacità totale suddivisa in livelli può essere scalata fino al limite del bucket del provider cloud. Sebbene la licenza non imponga restrizioni di capacità, seguire le https://www.netapp.com/pdf.html?item=/media/17239-tr-4598.pdf["Migliori pratiche FabricPool"^] per garantire prestazioni ottimali, affidabilità ed efficienza dei costi durante la configurazione e la gestione del tiering.

Per informazioni sui limiti di capacità di ciascun provider cloud, fare riferimento alla relativa documentazione:

* https://docs.aws.amazon.com/AmazonS3/latest/userguide/BucketRestrictions.html["Documentazione AWS"^]
* https://learn.microsoft.com/en-us/azure/storage/common/scalability-targets-standard-account["Documentazione di Azure per i dischi gestiti"^]E https://learn.microsoft.com/en-us/azure/storage/blobs/scalability-targets["Documentazione di Azure per l'archiviazione BLOB"^]
* https://cloud.google.com/storage/docs/buckets["Documentazione di Google Cloud"^]




[[max-number-of-systems]]
== Numero massimo di sistemi

La licenza basata sulla capacità limita ogni organizzazione NetApp Console a 24 sistemi Cloud Volumes ONTAP. Un sistema può essere una coppia HA Cloud Volumes ONTAP, un sistema Cloud Volumes ONTAP a nodo singolo o una VM di storage aggiuntiva che crei tu. La VM di storage predefinita non viene conteggiata ai fini del limite. Questo limite si applica a tutti i modelli di licensing.

Ad esempio, supponiamo di avere tre sistemi:

* Un sistema Cloud Volumes ONTAP a nodo singolo con una VM di storage (questa è la VM di storage predefinita creata quando si distribuisce Cloud Volumes ONTAP)
+
Questo sistema conta come un unico sistema.

* Un sistema Cloud Volumes ONTAP a nodo singolo con due VM di storage (la VM di storage predefinita, più una VM di storage aggiuntiva creata dall'utente)
+
Questo sistema conta come due sistemi: uno per il sistema a nodo singolo e uno per la storage VM aggiuntiva.

* Una coppia Cloud Volumes ONTAP HA con tre VM di storage (la VM di storage predefinita, più due VM di storage aggiuntive create dall'utente)
+
Questo sistema conta come tre sistemi: uno per la coppia HA e due per le VM di storage aggiuntive.



In totale sono sei sistemi. A quel punto nella tua organizzazione ci sarebbe spazio per altri 14 sistemi.

Se hai una grande implementazione che richiede più di 24 sistemi, contatta il tuo referente commerciale o il team di vendita.

Scopri i limiti di archiviazione per:

* AWS: link:reference-limits-aws.html["Limiti di archiviazione per Cloud Volumes ONTAP in AWS"]
* Azure: link:reference-limits-azure.html["Limiti di archiviazione per Cloud Volumes ONTAP in Azure"]
* Google Cloud: link:reference-limits-gcp.html["Limiti di storage per Cloud Volumes ONTAP in Google Cloud"]


.Link correlati
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/concept-licensing.html["Licenze per Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-capacity-licenses.html["Gestisci le licenze basate sulla capacità per Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-node-licenses.html["Gestisci le licenze basate sui nodi"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-convert-node-capacity.html["Convertire una licenza basata su nodi in una licenza basata sulla capacità"^]
* https://docs.netapp.com/us-en/storage-management-cloud-volumes-ontap/task-manage-keystone.html["Gestisci gli abbonamenti Keystone"^]

