---
sidebar: sidebar 
permalink: reference-versions.html 
keywords: versions, supported versions, new versions, cloud volumes ontap version 
summary: NetApp Console consente di scegliere tra diverse versioni ONTAP quando si crea un nuovo sistema Cloud Volumes ONTAP . 
---
= Versioni ONTAP supportate per le distribuzioni Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La NetApp Console consente di scegliere tra diverse versioni ONTAP quando si aggiunge un sistema Cloud Volumes ONTAP .

Le versioni di Cloud Volumes ONTAP diverse da quelle elencate qui non sono disponibili per nuove distribuzioni. La patch o la versione generica (General Availability) in una release qui rappresenta la versione base disponibile per la distribuzione. Per dettagli sulle patch disponibili, fare riferimento alle  https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-new.html["note di rilascio versionate"^] per ciascuna release.

Per informazioni sull'upgrade, fare riferimento a link:task-updating-ontap-cloud.html#supported-upgrade-paths["Percorsi di aggiornamento supportati"].

ifdef::aws[]



== AWS

Nodo singolo::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5
* 9.5 P6


--
coppia HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5
* 9.5 P6


--


endif::aws[]

ifdef::azure[]



== Azzurro

Nodo singolo::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--
coppia HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1 P3
* 9.15.1 P10
* 9.14.1 P13
* 9.13.1 P16
* 9.12.1 P18


--


endif::azure[]

ifdef::gcp[]



== Google Cloud

Nodo singolo::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8
* 9.7 P5


--
coppia HA::
+
--
* 9.18.1
* 9.17.1 P1
* 9.16.1
* 9.15.1
* 9.15.0 P1
* 9.14.1
* 9.14.1
* 9.14.0
* 9.13.1
* 9.12.1
* 9.12.1
* 9.12.0 P1
* 9.11.1 P3
* 9.10.1
* 9.9.1 P6
* 9,8


--


endif::gcp[]
