---
sidebar: sidebar 
permalink: reference-limitations-gcp.html 
keywords: limitations, google cloud platform, gcp, psc, private service connect 
summary: Le limitazioni note identificano piattaforme, dispositivi o funzioni che non sono supportati da questa versione del prodotto o che non interagiscono correttamente con esso. Esamina attentamente queste limitazioni. 
---
= Limitazioni note per Cloud Volumes ONTAP in Google Cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le seguenti limitazioni note sono specifiche di Cloud Volumes ONTAP in Google Cloud Platform. Assicurati di leggere anche link:reference-limitations.html["Limitazioni per Cloud Volumes ONTAP in tutti i provider cloud"].



[[limitation-with-packet-mirroring]]
== Limitazione con il mirroring dei pacchetti

https://cloud.google.com/vpc/docs/packet-mirroring["Mirroring dei pacchetti"^] must be disabled nella VPC di Google Cloud in cui distribuisci Cloud Volumes ONTAP.

Cloud Volumes ONTAP non può funzionare correttamente se il mirroring dei pacchetti è abilitato.



[[google-private-service-connect-limitations]]
== Limitazioni di Google Private Service Connect

Se si sfrutta  https://cloud.google.com/vpc/docs/private-service-connect["Google Private Service Connect"^] all'interno della VPC in cui si sta distribuendo Cloud Volumes ONTAP, sarà necessario implementare record DNS che inoltrano il traffico ai necessari  https://docs.netapp.com/us-en/bluexp-setup-admin/task-quick-start-connector-google.html["Endpoint API"^].

La suddivisione in livelli dei dati da Cloud Volumes ONTAP in un bucket Google Cloud Storage non è attualmente supportata con Private Service Connect.
