---
sidebar: sidebar 
permalink: reference-default-configs.html 
keywords: svm, LIF, LIFs, configuration backups, attributes, autosize, security style, space guarantee, unix permissions, NTFS, UNIX, boot, root, disks, aggr0, aggr1, svm, svms, storage virtual machine, LIF failover, failover, attributes, volume attributes, boot disk, root disk, licenses, feature licenses, default licenses, ontap licenses, ontap features 
summary: Comprendere come Cloud Volumes ONTAP è configurato per impostazione predefinita può aiutarti a configurare e amministrare i tuoi sistemi, soprattutto se hai familiarità con ONTAP , perché la configurazione predefinita per Cloud Volumes ONTAP è diversa da quella di ONTAP. 
---
= Configurazioni predefinite supportate per Cloud Volumes ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Comprendere come Cloud Volumes ONTAP è configurato per impostazione predefinita può aiutarti a configurare e amministrare i tuoi sistemi, soprattutto se hai familiarità con ONTAP , perché la configurazione predefinita per Cloud Volumes ONTAP è diversa da quella di ONTAP.



== Configurazione predefinita

* La console NetApp crea una VM di storage per la gestione dei dati quando distribuisce Cloud Volumes ONTAP.  Alcune configurazioni supportano VM di archiviazione aggiuntive. link:task-managing-svms.html["Scopri di più sulla gestione delle VM di archiviazione"] .
+
A partire dalla versione 3.9.5, la segnalazione dello spazio logico è abilitata sulla VM di archiviazione iniziale.  Quando lo spazio viene segnalato in modo logico, ONTAP segnala lo spazio del volume in modo tale che tutto lo spazio fisico risparmiato dalle funzionalità di efficienza di archiviazione venga segnalato come utilizzato.  Per informazioni sulle funzionalità di efficienza dell'archiviazione in linea, fare riferimento all'articolo della knowledge base https://kb.netapp.com/Cloud/Cloud_Volumes_ONTAP/What_Inline_Storage_Efficiency_features_are_supported_with_CVO#["KB: Quali funzionalità di Inline Storage Efficiency sono supportate da CVO?"^]

* La Console installa automaticamente le seguenti licenze delle funzionalità ONTAP su Cloud Volumes ONTAP:
+
** CIFS
** FlexCache
** FlexClone
** iSCSI
** Gestione delle chiavi di crittografia multi-tenant (MTEKM), a partire da Cloud Volumes ONTAP 9.12.1 GA
** NetApp Volume Encryption (solo per sistemi BYOL (Bring Your Own License) o PAYGO (Registered Pay-as-You-Go))
** NFS ifdef::aws[] endif::aws[] ifdef::azure[] endif::azure[]
** SnapMirror
** SnapRestore
** SnapVault


* Per impostazione predefinita vengono create diverse interfacce di rete:
+
** Un LIF di gestione dei cluster
** Un LIF intercluster




ifdef::azure[]

* Un LIF di gestione SVM su sistemi HA in Azure


endif::azure[]

ifdef::gcp[]

* Un LIF di gestione SVM su sistemi HA in Google Cloud


endif::gcp[]

ifdef::aws[]

* Un LIF di gestione SVM su sistemi a nodo singolo in AWS


endif::aws[]

* Un LIF di gestione dei nodi


ifdef::gcp[]

+ In Google Cloud, questo LIF è combinato con il LIF intercluster.

endif::gcp[]

* Un LIF di dati iSCSI
* Un LIF di dati CIFS e NFS
+

NOTE: Per impostazione predefinita, il failover LIF è disabilitato per Cloud Volumes ONTAP a causa dei requisiti del provider cloud.  La migrazione di un LIF su una porta diversa interrompe la mappatura esterna tra indirizzi IP e interfacce di rete sull'istanza, rendendo il LIF inaccessibile.

+
** Cloud Volumes ONTAP invia i backup della configurazione all'agente della console tramite HTTP.
+
I backup sono accessibili da \http://ipaddress/occm/offboxconfig/ dove _ipaddress_ è l'indirizzo IP dell'host dell'agente Console.

+
È possibile utilizzare i backup per riconfigurare il sistema Cloud Volumes ONTAP .  Per ulteriori informazioni sui backup di configurazione, fare riferimento a https://docs.netapp.com/us-en/ontap/system-admin/config-backup-file-concept.html["Documentazione ONTAP"^] .

** La Console imposta alcuni attributi del volume in modo diverso rispetto ad altri strumenti di gestione (ad esempio ONTAP System Manager o ONTAP CLI).
+
Nella tabella seguente sono elencati gli attributi del volume impostati in modo diverso dai valori predefiniti:

+
[cols="15,85"]
|===
| Attributo | Valore che la Console configura 


| Modalità di ridimensionamento automatico | crescere 


| Dimensione automatica massima  a| 
1.000 percento


NOTE: L'amministratore dell'organizzazione o dell'account può modificare questo valore dalla pagina Impostazioni.



| Stile di sicurezza | NTFS per volumi CIFS UNIX per volumi NFS 


| Stile di garanzia dello spazio | nessuno 


| Permessi UNIX (solo NFS) | 777 
|===
+
Per informazioni su questi attributi, fare riferimento alink:https://docs.netapp.com/us-en/ontap-cli-9121/volume-create.html["Pagina man ONTAP _volume create_"] .







== Dischi interni per i dati di sistema

Oltre allo spazio di archiviazione per i dati utente, la Console acquista anche spazio di archiviazione cloud per i dati di sistema.

ifdef::aws[]



=== AWS

* Tre dischi per nodo per dati di avvio, root e core:
+
** Disco io1 da 47 GiB per i dati di avvio
** Disco gp3 da 140 GiB per i dati di root
** Disco gp2 da 540 GiB per i dati principali


* Per coppie HA:
+
** Due volumi EBS st1 per l'istanza del mediatore, uno di circa 8 GiB come disco radice e uno di 4 GiB come disco dati
** Un disco gp3 da 140 GiB in ogni nodo per contenere una copia dei dati radice dell'altro nodo
+

NOTE: In alcune zone, il tipo di disco EBS disponibile può essere solo gp2.



* Uno snapshot EBS per ogni disco di avvio e disco di root
+

NOTE: Gli snapshot vengono creati automaticamente al riavvio.

* Quando si abilita la crittografia dei dati in AWS tramite Key Management Service (KMS), vengono crittografati anche i dischi di avvio e root per Cloud Volumes ONTAP .  Ciò include il disco di avvio per l'istanza del mediatore in una coppia HA.  I dischi vengono crittografati utilizzando la CMK selezionata quando si aggiunge un sistema Cloud Volumes ONTAP .



TIP: In AWS, la NVRAM si trova sul disco di avvio.

endif::aws[]

ifdef::azure[]



=== Azure (nodo singolo)

* Tre dischi SSD Premium:
+
** Un disco da 10 GiB per i dati di avvio
** Un disco da 140 GiB per i dati di root
** Un disco da 512 GiB per NVRAM
+
Se la macchina virtuale scelta per Cloud Volumes ONTAP supporta Ultra SSD, il sistema utilizza un Ultra SSD da 32 GiB per NVRAM anziché un Premium SSD.



* Un disco HDD standard da 1024 GiB per il salvataggio dei core
* Uno snapshot di Azure per ogni disco di avvio e disco radice
* Per impostazione predefinita, in Azure ogni disco è crittografato quando è inattivo.
+
Se la macchina virtuale scelta per Cloud Volumes ONTAP supporta Premium SSD v2 Managed Disk come disco dati, il sistema utilizza un Premium SSD v2 Managed Disk da 32 GiB per la NVRAM e un altro come disco radice.





=== Azzurro (coppia HA)

.HA si abbina al blob di pagina
* Due dischi SSD Premium da 10 GiB per il volume di avvio (uno per nodo)
* Due blob di pagina Premium Storage da 140 GiB per il volume radice (uno per nodo)
* Due dischi HDD standard da 1024 GiB per il salvataggio dei core (uno per nodo)
* Due dischi SSD Premium da 512 GiB per NVRAM (uno per nodo)
* Uno snapshot di Azure per ogni disco di avvio e disco radice
+

NOTE: Gli snapshot vengono creati automaticamente al riavvio.

* Per impostazione predefinita, in Azure ogni disco è crittografato quando è inattivo.


.Coppie HA con dischi gestiti condivisi in più zone di disponibilità
* Due dischi SSD Premium da 10 GiB per il volume di avvio (uno per nodo)
* Due dischi SSD Premium da 512 GiB per il volume root (uno per nodo)
* Due dischi HDD standard da 1024 GiB per il salvataggio dei core (uno per nodo)
* Due dischi SSD Premium da 512 GiB per NVRAM (uno per nodo)
* Uno snapshot di Azure per ogni disco di avvio e disco radice
+

NOTE: Gli snapshot vengono creati automaticamente al riavvio.

* Per impostazione predefinita, in Azure ogni disco è crittografato quando è inattivo.


.Coppie HA con dischi gestiti condivisi in singole zone di disponibilità
* Due dischi SSD Premium da 10 GiB per il volume di avvio (uno per nodo)
* Due dischi condivisi gestiti SSD Premium da 512 GiB per il volume root (uno per nodo)
* Due dischi HDD standard da 1024 GiB per il salvataggio dei core (uno per nodo)
* Due dischi gestiti SSD Premium da 512 GiB per NVRAM (uno per nodo)


Se la macchina virtuale supporta i dischi gestiti Premium SSD v2 come dischi dati, utilizza dischi gestiti Premium SSD v2 da 32 GiB per NVRAM e dischi gestiti condivisi Premium SSD v2 da 512 GiB per il volume root.

È possibile distribuire coppie HA in un'unica zona di disponibilità e utilizzare Premium SSD v2 Managed Disks quando sono soddisfatte le seguenti condizioni:

* La versione di Cloud Volumes ONTAP è 9.15.1 o successiva.
* La regione e la zona selezionate supportano i dischi gestiti Premium SSD v2.  Per informazioni sulle regioni supportate, fare riferimento a https://azure.microsoft.com/en-us/explore/global-infrastructure/products-by-region/["Sito Web di Microsoft Azure: prodotti disponibili per regione"^] .
* L'abbonamento è registrato per Microsoftlink:task-saz-feature.html["Funzionalità Microsoft.Compute/VMOrchestratorZonalMultiFD"] .


endif::azure[]

ifdef::gcp[]



=== Google Cloud (nodo singolo)

* Un disco persistente SSD da 10 GiB per i dati di avvio
* Un disco persistente SSD da 64 GiB per i dati di root
* Un disco persistente SSD da 500 GiB per NVRAM
* Un disco persistente standard da 315 GiB per il salvataggio dei core
* Snapshot per i dati di avvio e root
+

NOTE: Gli snapshot vengono creati automaticamente al riavvio.

* Per impostazione predefinita, i dischi di avvio e di root sono crittografati.




=== Google Cloud (coppia HA)

* Due dischi persistenti SSD da 10 GiB per i dati di avvio
* Quattro dischi SSD persistenti da 64 GiB per i dati di root
* Due dischi persistenti SSD da 500 GiB per NVRAM
* Due dischi persistenti standard da 315 GiB per il salvataggio dei core
* Un disco persistente standard da 10 GiB per i dati del mediatore
* Un disco persistente standard da 10 GiB per i dati di avvio del mediatore
* Snapshot per i dati di avvio e root
+

NOTE: Gli snapshot vengono creati automaticamente al riavvio.

* Per impostazione predefinita, i dischi di avvio e di root sono crittografati.


endif::gcp[]



=== Dove risiedono i dischi

Disposizione dello spazio di archiviazione:

* I dati di avvio risiedono su un disco collegato all'istanza o alla macchina virtuale.
+
Questo disco, che contiene l'immagine di avvio, non è disponibile per Cloud Volumes ONTAP.

* I dati radice, che contengono la configurazione e i registri del sistema, risiedono in aggr0.
* Il volume radice della macchina virtuale di archiviazione (SVM) risiede in aggr1.
* I volumi di dati risiedono anche in aggr1.

