---
sidebar: sidebar 
permalink: task-file-verification-mac.html 
keywords: Azure, image, VHD, file signature verification, encryption, sha256, ONTAP, Cloud Volumes, CLI, macOS 
summary: Verificare la firma di un file VHD esportato tramite lo strumento File digest immagine Cloud Volumes ONTAP su macOS 
---
= Verifica la firma dell'immagine di Azure Marketplace per Cloud Volumes ONTAP su macOS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La verifica della firma di un file VHD esportato su Linux include la convalida della catena di attendibilità, la modifica del file e la verifica della firma.

.Passi
. Scarica il file immagine di Azure da https://mysupport.netapp.com/site/["Sito di supporto NetApp"^] ed estrarre il file digest (.sig), il file del certificato della chiave pubblica (.pem) e il file del certificato della catena (.pem).
+
Fare riferimento a https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-azure-download-digest-file.html["Scarica il file digest dell'immagine di Azure"^] per maggiori informazioni.

. Verificare la catena di fiducia.
+
[source, cli]
----
% openssl verify -CAfile Certificate-Chain-9.15.0P1_azure.pem Certificate-9.15.0P1_azure.pem
Certificate-9.15.0P1_azure.pem: OK
----
. Rimuovere 1 MB (1.048.576 byte) all'inizio e 512 byte alla fine del file VHD.  Quando si utilizza `tail` , IL `-c +K` L'opzione genera byte dal K-esimo byte del file.  Pertanto, passa 1048577 a `tail -c` .  Tieni presente che su macOS il comando tail potrebbe richiedere circa dieci minuti per essere completato.
+
[source, cli]
----
% tail -c +1048577 ./9150.01000024.05090105.vhd > ./sign.tmp.tail
% head -c -512 ./sign.tmp.tail > sign.tmp
% rm ./sign.tmp.tail
----
. Utilizzare OpenSSL per estrarre la chiave pubblica dal certificato e verificare il file estratto (sign.tmp) con il file della firma e la chiave pubblica.  Il prompt dei comandi visualizza messaggi che indicano l'esito positivo o negativo della verifica.
+
[source, cli]
----
% openssl x509 -pubkey -noout -in ./Certificate-9.15.0P1_azure.pem > ./Code-Sign-Cert-Public-key.pub

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./sign.tmp
Verified OK

% openssl dgst -verify Code-Sign-Cert-Public-key.pub -keyform PEM -sha256 -signature digest.sig -binary ./another_file_from_nowhere.tmp
Verification Failure
----
. Pulisci l'area di lavoro.
+
[source, cli]
----
% rm ./9150.01000024.05090105.vhd ./sign.tmp
% rm *.sig *.pub *.pem
----

