---
sidebar: sidebar 
permalink: task-encrypting-volumes.html 
keywords: encrypt, encryption, data, volumes, netapp volume encryption, volume encryption, nve, key managers, kmip, key management servers, license, ssl certificates, nae, netapp aggregate encryption 
summary: 'Cloud Volumes ONTAP supporta sia NetApp Volume Encryption (NVE) sia NetApp Aggregate Encryption (NAE) con un gestore di chiavi esterno.  NVE e NAE sono abilitati per impostazione predefinita se si imposta un gestore di chiavi esterno.' 
---
= Crittografa i volumi su Cloud Volumes ONTAP con le soluzioni di crittografia NetApp
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Volumes ONTAP supporta NetApp Volume Encryption (NVE) e NetApp Aggregate Encryption (NAE).  NVE e NAE sono soluzioni basate su software che consentono la crittografia dei dati a riposo dei volumi conforme allo standard FIPS 140-2. link:concept-security.html["Scopri di più su queste soluzioni di crittografia"] .

Sia NVE che NAE sono supportati da un gestore di chiavi esterno.

Se utilizzi NVE, hai la possibilità di utilizzare il key vault del tuo provider cloud per proteggere le chiavi di crittografia ONTAP :

* AWS Key Management Service (a partire dalla versione 9.12.0)
* Azure Key Vault (AKV)
* Servizio di gestione delle chiavi di Google Cloud


I nuovi aggregati avranno NAE abilitato per impostazione predefinita dopo aver configurato un Key Management Service esterno. I nuovi volumi che non fanno parte di un aggregato NAE avranno NVE abilitato per impostazione predefinita (ad esempio, se hai aggregati esistenti creati prima di configurare un Key Management Service esterno).

Cloud Volumes ONTAP non supporta la gestione delle chiavi integrata.

.Prima di iniziare
Il tuo sistema Cloud Volumes ONTAP deve essere registrato con il supporto NetApp. Una licenza NetApp Volume Encryption viene installata automaticamente su ciascun sistema Cloud Volumes ONTAP registrato con il supporto NetApp.

* https://docs.netapp.com/us-en/console-setup-admin/task-adding-nss-accounts.html["Aggiunta degli account del sito di supporto NetApp alla console"^]
* link:task-registering.html["Registrare i sistemi pay-as-you-go"]



NOTE: La NetApp Console non installa la licenza NVE sui sistemi che si trovano nella regione Cina.

.Passi
. Esamina l'elenco dei gestori di chiavi supportati nel http://mysupport.netapp.com/matrix["Strumento matrice di interoperabilità NetApp"^].
+

TIP: Cerca la soluzione *Key Managers*.

. link:task-connecting-to-otc.html["Connettiti alla CLI di Cloud Volumes ONTAP"^].
. Configura la gestione delle chiavi esterne.
+
** AWS: link:task-aws-key-management.html["Servizio di gestione delle chiavi AWS"]
** Azure: link:task-azure-key-vault.html["Azure Key Vault (AKV)"]
** Google Cloud: link:task-google-key-manager.html["Servizio di gestione delle chiavi di Google Cloud"]



