---
sidebar: sidebar 
permalink: task-sync-time.html 
keywords: set up, setting up, ntp, time, synch 
summary: 'Specificando un server NTP si sincronizza l"ora tra i sistemi nella rete, il che può aiutare a prevenire problemi dovuti alle differenze di fuso orario.' 
---
= Sincronizza l'ora di sistema di Cloud Volumes ONTAP utilizzando i server NTP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La configurazione dei server Network Time Protocol (NTP) per i cluster Cloud Volumes ONTAP garantisce una sincronizzazione accurata dell'ora del cluster con altri sistemi nella rete e con server esterni. La sincronizzazione dell'ora del cluster con server NTP esterni aiuta a mantenere la coerenza nell'infrastruttura. NetApp configura i server NTP per impostazione predefinita per le nuove distribuzioni Cloud Volumes ONTAP. Tuttavia, se non sono configurati per i cluster Cloud Volumes ONTAP esistenti, è necessario configurare i server NTP per una sincronizzazione accurata dell'ora all'interno e all'esterno della rete.

È possibile specificare un server NTP utilizzando:

* https://docs.netapp.com/us-en/bluexp-automation/cm/api_ref_resources.html["L'API NetApp Console"^].
* Il comando CLI ONTAP https://docs.netapp.com/us-en/ontap-cli//cluster-time-service-ntp-server-create.html["creazione del server NTP del servizio orario del cluster"^].



NOTE: Se non si configura un server NTP, potrebbero verificarsi interruzioni del servizio e una sincronizzazione oraria imprecisa.

.Link correlati
* Articolo della Knowledge Base (KB): https://kb.netapp.com/Cloud/ncds/nds/cvo/cvo_kbs/How_does_a_CVO_cluster_use_NTP["In che modo un cluster CVO utilizza NTP?"]
* https://docs.netapp.com/us-en/bluexp-automation/cm/prepare.html["Preparati a utilizzare l'API"^]
* https://docs.netapp.com/us-en/bluexp-automation/cm/workflow_processes.html#organization-of-cloud-volumes-ontap-workflows["Flussi di lavoro Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/get_identifiers.html#get-the-connector-identifier["Ottieni gli identificatori richiesti"^]
* https://docs.netapp.com/us-en/bluexp-automation/platform/use_rest_apis.html["Utilizzare le API REST per NetApp Console"^]

