= Fine della disponibilità delle licenze basate su nodi
:allow-uri-read: 




=== Fine della disponibilità delle licenze basate su nodi

NetApp ha pianificato la fine della disponibilità (EOA) e la fine del supporto (EOS) delle licenze basate sui nodi Cloud Volumes ONTAP .  A partire dall'11 novembre 2024, la disponibilità limitata delle licenze basate sui nodi è terminata. Il supporto per le licenze basate sui nodi termina il 31 dicembre 2024.  Dopo l'EOA delle licenze basate sui nodi, dovresti passare alle licenze basate sulla capacità utilizzando lo strumento di conversione delle licenze BlueXP .

Per impegni annuali o a lungo termine, NetApp consiglia di contattare il proprio rappresentante NetApp prima della data di EOA o della data di scadenza della licenza per assicurarsi che siano soddisfatti i prerequisiti per la transizione.  Se non si dispone di un contratto a lungo termine per un nodo Cloud Volumes ONTAP e si esegue il sistema con un abbonamento on-demand pay-as-you-go (PAYGO), è importante pianificare la conversione prima della data di fine del supporto.  Sia per i contratti a lungo termine che per gli abbonamenti PAYGO, puoi utilizzare lo strumento di conversione delle licenze BlueXP per una conversione senza interruzioni.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Fine della disponibilità delle licenze basate sui nodi"^] https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/task-convert-node-capacity.html["Convertire una licenza basata su nodi Cloud Volumes ONTAP in una licenza basata sulla capacità"^]



=== Rimozione delle distribuzioni basate su nodi da BlueXP

L'opzione per distribuire sistemi Cloud Volumes ONTAP utilizzando licenze basate su nodi è obsoleta su BlueXP.  Ad eccezione di alcuni casi particolari, non è possibile utilizzare licenze basate su nodi per le distribuzioni Cloud Volumes ONTAP per nessun provider cloud.

NetApp riconosce i seguenti requisiti di licenza univoci in conformità con gli obblighi contrattuali e le esigenze operative e continuerà a supportare le licenze basate su nodi in queste situazioni:

* Clienti del settore pubblico statunitense
* Distribuzioni in modalità privata
* Distribuzioni nella regione cinese di Cloud Volumes ONTAP in AWS
* Se hai una licenza BYOL (licenza BY-NODE) valida e non scaduta


https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-licensing.html#end-of-availability-of-node-based-licenses["Fine della disponibilità delle licenze basate sui nodi"^]



=== Aggiunta di un livello freddo per i dati Cloud Volumes ONTAP nell'archiviazione BLOB di Azure

BlueXP ora consente di selezionare un livello freddo per archiviare i dati del livello di capacità inattivo nell'archiviazione BLOB di Azure.  Aggiungendo il livello freddo ai livelli caldo e freddo esistenti, si ottiene un'opzione di stoccaggio più conveniente e una migliore efficienza dei costi.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-data-tiering.html#data-tiering-in-azure["Livelli dei dati in Azure"^]



=== Opzione per limitare l'accesso pubblico all'account di archiviazione per Azure

Ora hai la possibilità di limitare l'accesso pubblico al tuo account di archiviazione per i sistemi Cloud Volumes ONTAP in Azure.  Disabilitando l'accesso, puoi proteggere il tuo indirizzo IP privato dall'esposizione anche all'interno della stessa rete virtuale, qualora fosse necessario rispettare le policy di sicurezza della tua organizzazione.  Questa opzione disabilita anche la suddivisione in livelli dei dati per i sistemi Cloud Volumes ONTAP ed è applicabile sia ai nodi singoli che alle coppie ad alta disponibilità.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/reference-networking-azure.html#security-group-rules["Regole del gruppo di sicurezza"^] .



=== Abilitazione WORM dopo la distribuzione di Cloud Volumes ONTAP

Ora è possibile attivare l'archiviazione WORM (Write Once, Read Many) su un sistema Cloud Volumes ONTAP esistente utilizzando BlueXP.  Questa funzionalità offre la flessibilità di abilitare WORM su un ambiente di lavoro, anche se WORM non è stato abilitato su di esso durante la sua creazione.  Una volta abilitato, non è possibile disabilitare WORM.

https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/concept-worm.html#enabling-worm-on-a-cloud-volumes-ontap-working-environment["Abilitazione di WORM su un ambiente di lavoro Cloud Volumes ONTAP"^]
